CREATE TABLE STUDENT
(
    SNO   varchar(50)  NOT NULL,
    SNAME varchar(255) NOT NULL,
    SSEX  varchar(50)  NOT NULL
);
INSERT INTO STUDENT
VALUES ('001', 'KangKang', 'M ');
INSERT INTO STUDENT
VALUES ('002', 'Mike', 'M ');
INSERT INTO STUDENT
VALUES ('003', 'Jane', 'F ');